### ISSUE TITLE
Add `Login with GitHub`

### ISSUE THREAD

**Issue by carusogabriel** [jgrossi/elephpant.me#103]
Hey folks!

Would you accept a PR adding support to `Login with GitHub`, something like:

![image](https://user-images.githubusercontent.com/16328050/113446936-2d3c5300-93f9-11eb-90e3-44b5373f562e.png)

to `https://elephpant.me/login`? 😄

**Comment by jgrossi** [comment]
hey mate! of course ❤️ go ahead!
