### ISSUE TITLE
New php[architect] elePHPant

### ISSUE THREAD

**Issue by asgrim** [jgrossi/elephpant.me#145]
https://www.phparch.com/swag/plush-elephpant/

Seems there is a new edition with "I'm a php[architect]" (previous version only had the logo)

**Comment by cookieguru** [comment]
I think we should track this separately from the original edition

**Comment by cookieguru** [comment]
@jgrossi @IgorSantos17 what do you think?

**Comment by nauleyco** [comment]
I agree with managing them as separate version.
Differences between the 2014 and 2022. 
<img width="921" alt="differences_2014and2022" src="https://user-images.githubusercontent.com/28845/178479138-eaaf7987-9441-4529-8c6a-730355ec80cd.png">

**Comment by derickr** [comment]
The photos on the site are still the same though...

**Comment by cookieguru** [comment]
...well that was my bad for using the same image.  But this is very confusing since [the code lists it as number 14](https://github.com/jgrossi/elephpant.me/blob/master/resources/data/elephpants.json#L107-L114) but [the site lists it as number 8](https://elephpant.me/)

**Comment by cookieguru** [comment]
@jgrossi which branch/commit is deployed on production?
