### ISSUE TITLE
Missing elePHPants

### ISSUE THREAD

**Issue by asgrim** [jgrossi/elephpant.me#16]
CakeDC and CakeFest elePHPants are missing.

**Comment by IgorSantos17** [comment]
Missing PHPCon Poland older
[image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5KM0XmbU2Y7pMdTMU67MB6IBPQ3_smvT_CdOuF_ZUYA1YN3LJjA&s)

**Comment by IgorSantos17** [comment]
There is also a new elephant from PHPCon Japan 2019
[image](https://base-ec2if.akamaized.net/w=500,a=0,q=90,u=1/images/item/origin/b6ea5123ac82da94f966f285ba1a42d6.jpg)

**Comment by jgrossi** [comment]
we have just added SymfonyCon 2019 gray elePHPant. @IgorSantos17 will raise a PR to add CakeDC, CakeFest, PHPCon Poland and PHPCon Japan 2019 👍

**Comment by IgorSantos17** [comment]
In the coming days I will be sending the PR.

**Comment by jgrossi** [comment]
@asgrim @IgorSantos17 PHP Conference Japan 2019 added 🎉

**Comment by jgrossi** [comment]
UPDATE: CakeDC and CakeFest elePHPants were also added ❤️
