### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by teiling88** [jgrossi/elephpant.me#161]
Hey Folks, 

has somebody information about @jgrossi. SInce 9 months I didn't receive any message on twitter etc. Is this great project dead?

Kind Regards,
Thomas

**Comment by jgrossi** [comment]
Hey,  no the project is not dead. I’m just having some time off from social networks. Happy to add people here to help with the project. @teiling88 can I add you to the repo so you can help with issues and PRs?

**Comment by teiling88** [comment]
Hey, 
great to read you :-) 

Ok, I didn't know. I hope you recovered completly. Sounds like a good plan. Thank you for your trust! 

If you want, my sponsorship offer is still open. So I can handle for you the server administration stuff if you want. We could automate the deployment etc :-)

Kind Regards, 
Thomas

**Comment by teiling88** [comment]
Hey @jgrossi, 
everything fine? :-) 
Greetings, Thomas

**Comment by teiling88** [comment]
Ping?

**Comment by jgrossi** [comment]
hey mate :D just added you to the repo, sorry for the delay
