### ISSUE TITLE
Statistics about elephpants

### ISSUE THREAD

**Issue by pgrimaud** [jgrossi/elephpant.me#27]
Hi,

What do you think about adding a page with statistics about elephpants?

For example : 
- elePHPant owned by XXX people
- elePHPant owned by X% of people
- etc.

If it could be relevant, let's talk about and I will make a PR with this feature.

Cheers

**Comment by IgorSantos17** [comment]
Hey @pgrimaud 
sorry, i didn't quite understand how relevant this information can be

**Comment by jgrossi** [comment]
@pgrimaud @IgorSantos17 IMHO it seems a good information. It would be good to have this for a dashboard I see. It would be good to know most missing elephpants, the ones everyone has. it's an start point for the "shop" functionality we have plans to implement.

@pgrimaud let's start simple, so a "Statistics" page would be good. we can go from there. my only concerns is about how is the best way to do that in terms of UI. but this is up to you @pgrimaud. thanks

**Comment by pgrimaud** [comment]
> It would be good to know most missing elephpants, the ones everyone has.

That's exactly the idea. I will start with something simple and we could add data afterwards.

**Comment by IgorSantos17** [comment]
this started to get interesting, we can map which species are rare and which are common

**Comment by pgrimaud** [comment]
I added a page with a table ordering elephants by percent of **ownership** (or **adoption**, I'm not sure about the word).
It's very simple view, you can take a look a it and ask for changes or edit it as your needs.

**Comment by pgrimaud** [comment]
I rewrite ownership statistics calculation.

Actually, the "Ownership percentage" is calculated with all users registered on website.
With PR #31 "Ownership percentage" will be calculate with all users registered on website with at least 1 elePHPant on their herd.

**Comment by jgrossi** [comment]
thanks @pgrimaud merged! 🎉
