### ISSUE TITLE
pHackyderm

### ISSUE THREAD

**Issue by pgrimaud** [jgrossi/elephpant.me#32]
Why is "pHackyderm" listed on this website?

It was a prototype from 2015, but never mass produced. I'm not sure about it but according to this [page](https://elephpant.me/statistics), no one owns this elePHPant yet.

**Comment by jgrossi** [comment]
according to this tweet we do have some, somewhere 😂 https://twitter.com/sprunka/status/1094678911219306496, and of course, not everyone is on elephpant.me yet 🔥

**Comment by pgrimaud** [comment]
Almost 1 year ago! So mysterious 😂🤔🕵️‍♂️

So we'll wait and see. Thank you for clarification. 😄
