### ISSUE TITLE
Show trade options on users page

### ISSUE THREAD

**Issue by doppynl** [jgrossi/elephpant.me#46]
Would be useful if you visit a users page with their collection, it shows you trade options you have with that user.
Now you have to go to the trade area.

- show double elephpants that loggedin user does not have. ie: "Doubles you don't have yet"
- show double elephpants of loggedin user that displayed user does not have. ie: "Your doubles this user might be interested in".

**Comment by IgorSantos17** [comment]
I don't think that makes sense, as this is already the goal of the trade area.
the collection page is just to appreciate the user's collection.

**Comment by doppynl** [comment]
can be very useful if somebody asks for a trade and you want to figure out what elephpant you want in return for the trade.
At the moment you have to locate the user that send you the request on multiple pages in the trade area.

**Comment by jgrossi** [comment]
I agree with @doppynl 🤔 it makes sense to me. it's useful to have a quick "box" showing something like "you can trade X and Y with this user" or just "you don't have anything to offer to the user for trading" just ideas 👍

**Comment by IgorSantos17** [comment]
maybe something like that could be implemented in the trade area.
I don't think it makes sense to "pollute" the user's collection page.

**Comment by jgrossi** [comment]
@IgorSantos17 I think you didn't get the whole idea haha. think this scenario: I'm at the ranking, then I see Igor with X elephpants there. we already have a link to the profile page, but when you open it you see only the units the user has.

the idea is to also add along with the elephpants which one you could trade with the user. also, for the "shopping feature" we could have there a list of elephpants the user is selling, not only trading. 

I really think it's a good idea
