### ISSUE TITLE
Handmade elePHPants?

### ISSUE THREAD

**Issue by sc0ttkclark** [jgrossi/elephpant.me#53]
As more handmade elePHPants enter the "market" of various quality, should those somehow be allowed for entry on the site? Such as submitting the photo along with who it was produced by?

That could be a custom per-herd entry, or maybe it would be global. Not sure what constitutes an official species. Does it have to have a logo on the right side?

**Comment by jgrossi** [comment]
@sc0ttkclark this is a very fair point IMO. I think this should be a decision made by the community TBH. my personal opinion is that we "should have" only elephpants approved by Vincent Pontier (aka Elroubio) http://twitter.com/elroubio, but not sure if all elephpants we have here were approved by him already

**Comment by sc0ttkclark** [comment]
I came to find out the majority of the handmade ones don't count. I had no idea there was an approval process or an official bar of requirements that had to be met. You can close this probably, but it would be good to get confirmation all those included are verified by Vincent.

**Comment by IgorSantos17** [comment]
I believe we have all the local elephpants by communities or groups, I think it makes sense to keep these, because they are elephpants that everyone has a chance of getting one.

**Comment by jgrossi** [comment]
@sc0ttkclark can you give please an example of a handmade one please?

**Comment by sc0ttkclark** [comment]
I think it makes sense to list out community ones too, but there's a very fine line between what a ElePHPant is and what an Elephant with PHP on the side and another logo on it is. If they are official, we should put our support behind them. If they aren't, that's risking giving the impression that they are official.

**Comment by jgrossi** [comment]
yep gonna try to reach Vincent regarding of what are the official ones. I know we have the field guide website but also not sure they're updated as well
