### ISSUE TITLE
Siteground elePHPant

### ISSUE THREAD

**Issue by pgrimaud** [jgrossi/elephpant.me#59]
Hello @jgrossi @IgorSantos17

It seems there's a new cowboy in town. 😎

 ![image](https://user-images.githubusercontent.com/1866496/95581893-10baf180-0a3a-11eb-8e15-2bcb1c4c7848.png)

https://www.siteground.com/blog/php8/

I opened this issue until getting more informations about it.

**Comment by jgrossi** [comment]
loved the design! 😍

**Comment by ymihaylov** [comment]
I have the elePHPant. His name is **SiteGround elePHPant** and he is born in 2020. How can add him to the list? :)

**Comment by IgorSantos17** [comment]
Hey @ymihaylov sorry for the misspellings, I already merge your correction, thanks.

**Comment by ymihaylov** [comment]
Okay, thanks! I can't wait to see it live! :)
