### ISSUE TITLE
Profile Card

### ISSUE THREAD

**Issue by IgorSantos17** [jgrossi/elephpant.me#61]
Change the profile information to card format adding the twitter avatar from user.
If user has a twitter registered, show the profile picture
Otherwise, will be catch the first letter from first and last name from the user and display in the same format

currently there is open PR #13  by @omarkdev , more is still incomplete.

**Comment by g1dra** [comment]
Hi. I'm interested in helping with this issue. Do you have access to Twitter API or how do you plan do get profile image ?

**Comment by pgrimaud** [comment]
You could also try the Gravatar API?

**Comment by jgrossi** [comment]
closing due to #70
