### ISSUE TITLE
Errors on statistics page

### ISSUE THREAD

**Issue by pgrimaud** [jgrossi/elephpant.me#66]
Hi @jgrossi,

I found an error on statistics page : 

![image](https://user-images.githubusercontent.com/1866496/96353597-cf77b100-10cd-11eb-8261-0acbcec88268.png)

We can't have 12 users with 11 elePHPants right ?

But what happened? Could you check directly in production database? Thanks

**Comment by IgorSantos17** [comment]
I discovered the problem, a user reported that he has 0 of an elephpant, so he appears in the list and in the statistics.

**Comment by IgorSantos17** [comment]
I opened issue #75 specific for this problem, so I am closing this one.

**Comment by pgrimaud** [comment]
> I discovered the problem, a user reported that he has 0 of an elephpant, so he appears in the list and in the statistics.

Ohh ok! I could'nt reproduce it on own side.

**Comment by jgrossi** [comment]
this PR should fix it #76
