### ISSUE TITLE
Idea: Make it easier for members to find elePHPants (if possible)

### ISSUE THREAD

**Issue by asgrim** [jgrossi/elephpant.me#88]
Some elePHPants are commercially (regular blue/pink), or crowd-funded available (inPHPinity), or perhaps through contribution schemes (SiteGround).

For those wanting to get started on their collections, perhaps link to, or explain how to acquire each particular elePHPant on the "My Herd" page (https://elephpant.me/my-herd).

For the plushies that aren't readily available, just a link perhaps saying the number of trades available (`%d trades available`) or something if a trade is available, and link to the trades page.

An example of what I'm thinking of (note: the data might not be accurate, it's just a mockup!):

![Screenshot from 2020-12-03 08-47-26](https://user-images.githubusercontent.com/496145/100985753-3d741c80-3544-11eb-906a-b1503259d052.png)

**Comment by jgrossi** [comment]
released along with #104. thanks @Wilkins
