### ISSUE TITLE
PHP Classes elePHPants

### ISSUE THREAD

**Issue by pgrimaud** [jgrossi/elephpant.me#93]
Hi,

I got the two different models of PHP Classes.

Not really an issue, but FYI. Ref to #47.

Left is the new "PHP Classes 2020", right is the "Original one" :

![image](https://user-images.githubusercontent.com/1866496/101362825-ebfbc280-38a0-11eb-9736-95fd0fe6a148.png)

![image](https://user-images.githubusercontent.com/1866496/101362950-0fbf0880-38a1-11eb-99b1-a9e1df5af468.png)

![image](https://user-images.githubusercontent.com/1866496/101362974-15b4e980-38a1-11eb-8a06-6de54eb4f4e5.png)

![image](https://user-images.githubusercontent.com/1866496/101362988-19e10700-38a1-11eb-9ff0-e8812d103b4e.png)

**Comment by IgorSantos17** [comment]
Hey @pgrimaud 
I talked with @jgrossi about it and decided to keep the photo of the last elephpant, because the same elephpants are just variations of productions.

**Comment by pgrimaud** [comment]
Yes of course.

IDKW, but I can't upload pictures on closed PR or issue... I just posted it as a new issue for history.

It may be useful for IT historians in a long future. 😂
